Gentoo: cleanup for ltsp-build-client files; tabs to spaces, shorthand ifs in profile and set some defaults in plugins.

diff --git a/server/share/ltsp/plugins/ltsp-build-client/Gentoo/010-bootstrap b/server/share/ltsp/plugins/ltsp-build-client/Gentoo/010-bootstrap
--- a/server/share/ltsp/plugins/ltsp-build-client/Gentoo/010-bootstrap
+++ b/server/share/ltsp/plugins/ltsp-build-client/Gentoo/010-bootstrap
@@ -6,21 +6,21 @@ case "$MODE" in
         add_option "installer-verbose" "`eval_gettext "Show installer external command output"`" "advanced" "false"
     ;;
     configure)
-		if [ -n "$option_installer_value" ] || [ -n "$INSTALLER" ]; then
-			INSTALLER=${option_installer_value:-$INSTALLER}
+        if [ -n "$option_installer_value" ] || [ -n "$INSTALLER" ]; then
+            INSTALLER=${option_installer_value:-$INSTALLER}
 
-			case "$INSTALLER" in 
-			quickstart|kicktoo)
-				printf "`eval_gettext "Using installer: %s"`\n" $INSTALLER ;;
-            *)			
-				printf "`eval_gettext "ERROR: unsupported installer. Check your --installer argument: %s"`\n", $INSTALLER
-				printf "`eval_gettext "       supported values are: %s"`\n", "quickstart kicktoo"
-				exit 1
-			esac
-		else
-			INSTALLER="kicktoo"
-			printf "`eval_gettext "Using installer: %s"`\n" $INSTALLER
-		fi
+            case "$INSTALLER" in 
+                quickstart|kicktoo)
+                    printf "`eval_gettext "Using installer: %s"`\n" $INSTALLER ;;
+                *)
+                    printf "`eval_gettext "ERROR: unsupported installer. Check your --installer argument: %s"`\n", $INSTALLER
+                    printf "`eval_gettext "       supported values are: %s"`\n", "quickstart kicktoo"
+                    exit 1
+            esac
+        else
+            INSTALLER="kicktoo"
+            printf "`eval_gettext "Using installer: %s"`\n" $INSTALLER
+        fi
 
         if [ -n "$option_installer_profile_value" ] || [ -n "$INSTALLER_PROFILE" ]; then
             INSTALLER_PROFILE=${option_installer_profile_value:-$INSTALLER_PROFILE}
@@ -45,7 +45,7 @@ case "$MODE" in
     ;;
     install)
         printf "`eval_gettext "Installing into: %s"`\n" $ROOT
-        
+
         # TODO: figure out why we need to set ROOT=""
         # ROOT is somehow used in emerge, causing emerged installs
         # to go into /chroot/chroot, resetting until quickstart is done.
@@ -59,7 +59,7 @@ case "$MODE" in
         INITRAMFS_BUILDER="${INITRAMFS_BUILDER}" \
         VIDEO_CARDS="${VIDEO_CARDS}" INPUT_DEVICES="${INPUT_DEVICES}" \
         $INSTALLER $INSTALLER_ARGS $INSTALLER_PROFILE
-        
+
         # And reset to the original value
         ROOT=${TEMPROOT}
     ;;
