include X02-localapps-menu into X01-localapps

diff --git a/localapps/ldm-rc.d/X01-localapps b/localapps/ldm-rc.d/X01-localapps
--- a/localapps/ldm-rc.d/X01-localapps
+++ b/localapps/ldm-rc.d/X01-localapps
@@ -104,13 +104,27 @@ if boolean_is_true "$LOCAL_APPS"; then
     sshfs -o allow_other,ControlPath=${LDM_SOCKET} ${LDM_SERVER}:${LDM_HOME} ${LDM_HOME}
 
     # Create tmpdir for localapps menu
-    if boolean_is_true "$LOCAL_APPS_MENU"; then
+    if boolean_is_true "$LOCAL_APPS_MENU" && [ -x "/usr/bin/ltsp-genmenu" ]; then
         TMP_XDG_MENU="$(ssh -S ${LDM_SOCKET} ${LDM_SERVER} mktemp -d /tmp/ltsp-localapps-${LDM_USERNAME}-XXXXXX)"
         export TMP_XDG_MENU
         # Make the working directory and subdirs
         TMP_XDG_DIR_LOCAL="$(mktemp -d /tmp/ltsp-localapps-${LDM_USERNAME}-XXXXXX)"
         export TMP_XDG_DIR_LOCAL
         CLIENT_ENV="${CLIENT_ENV} XDG_DATA_DIRS=${TMP_XDG_MENU}/:/usr/local/share/:/usr/share/"
+
+        # Generate the localapp menu
+
+        # chown the tmpdir to be owned by the user
+        # FIXME: assumes user/group are identical
+        chown -R ${TMP_XDG_DIR_LOCAL} ${LDM_USERNAME}:${LDM_USERNAME}
+
+        su - ${LDM_USERNAME} -c "LOCAL_APPS_MENU_ITEMS=${LOCAL_APPS_MENU_ITEMS} /usr/bin/ltsp-genmenu install"
+
+        # now, scp the directory to the /tmp dir on the server
+        scp -r -o "ControlPath $LDM_SOCKET" -o "User $LDM_USERNAME" ${TMP_XDG_DIR_LOCAL}/* ${LDM_SERVER}:${TMP_XDG_MENU}
+
+        # Clean up local
+        rm -rf ${TMP_XDG_DIR_LOCAL} || true
     fi
 
     #Launch the ltsp-localappsd to handle the apps
