Allow 2 parameters in run_parts_list.

diff --git a/ltsp-common-functions b/ltsp-common-functions
--- a/ltsp-common-functions
+++ b/ltsp-common-functions
@@ -18,7 +18,7 @@ boolean_is_true(){
 # $1 - directory to list
 # $2 - optional prefix to limit which files are selected
 run_parts_list() {
-    test $# -eq 1 || die "ERROR: Usage: run_parts_list <dir>"
+    test $# -ge 1 || die "ERROR: Usage: run_parts_list <dir>"
     if [ -d "$1" ]; then
         find -L "$1" -mindepth 1 -maxdepth 1 -type f -name "$2*" |
             sed -n '/.*\/[0-9a-zA-Z_\-]\{1,\}$/p' | sort -n
