ltsp-common-functions: if $1 is not a dir, echo nothing.

diff --git a/ltsp-common-functions b/ltsp-common-functions
--- a/ltsp-common-functions
+++ b/ltsp-common-functions
@@ -18,16 +18,11 @@ boolean_is_true(){
 # $1 - directory to list
 # $2 - optional prefix to limit which files are selected
 run_parts_list() {
-    if [ $# -lt 1 ]; then
-        echo "ERROR: Usage: run_parts_list <dir>" > /dev/stderr
-        exit 1
+    test $# -eq 1 || die "ERROR: Usage: run_parts_list <dir>"
+    if [ -d "$1" ]; then
+        find -L "$1" -mindepth 1 -maxdepth 1 -type f -name "$2*" |
+            sed -n '/.*\/[0-9a-zA-Z_\-]\{1,\}$/p' | sort -n
     fi
-    if [ ! -d "$1" ]; then
-        echo "ERROR: Not a directory: $1" > /dev/stderr
-        exit 1
-    fi
-
-    find -L "$1" -mindepth 1 -maxdepth 1 -type f -name "$2*" | sed -n '/.*\/[0-9a-zA-Z_\-]\{1,\}$/p' | sort -n
 }
 
 detect_vendor() {
