move run_parts_list function into ltsp-common-functions

diff --git a/ltsp-common-functions b/ltsp-common-functions
--- a/ltsp-common-functions
+++ b/ltsp-common-functions
@@ -8,6 +8,29 @@ boolean_is_true(){
     esac
 }
 
+# list files in a directory consisting only of alphanumerics, hyphens and
+# underscores
+# $1 - directory to list
+run_parts_list() {
+    if [ $# -lt 1 ]; then
+        echo "ERROR: Usage: run_parts_list <dir>" > /dev/stderr
+        exit 1
+    fi
+    if [ ! -d "$1" ]; then
+        echo "ERROR: Not a directory: $1" > /dev/stderr
+        exit 1
+    fi
+
+    if [ -d "$1" ]; then
+        for file in $(find -L $1 -mindepth 1 -maxdepth 1 -type f | sort -n) ; do
+            basefile=$(basename $file)
+            if [ -n "$(echo "$basefile" | egrep ^[0-9a-zA-Z_\-]*$)" ]; then
+                echo $file
+            fi
+        done
+    fi
+}
+
 if [ -f /usr/share/ltsp/ltsp-vendor-functions ]; then
     . /usr/share/ltsp/ltsp-vendor-functions
 fi
