New ltsp-common-functions: die, require_root, mark_mount, umount_marked.

diff --git a/ltsp-common-functions b/ltsp-common-functions
--- a/ltsp-common-functions
+++ b/ltsp-common-functions
@@ -1,5 +1,10 @@
 # Common functions shared by LTSP scripts
 
+die() {
+    echo "$@" >&2
+    exit 1
+}
+
 boolean_is_true(){
     case $1 in
        # match all cases of true|y|yes
@@ -32,6 +37,52 @@ detect_vendor() {
     else
         echo $(lsb_release --id --short | tr " " "_")
     fi
+}
+
+require_root()
+{
+    if [ ${UID:-$(id -u)} -ne 0 ]; then
+        die "Superuser privileges are needed."
+    fi
+}
+
+# Remember mounted dirs so that it's easier to unmount them with a single call
+# to umount_marked. They'll be unmounted in reverse order.
+# Use the normal mount syntax, e.g.
+#   mark_mount -t proc proc "$ROOT/proc"
+mark_mount() {
+    local dir
+
+    # The last parameter is the dir we need to remember to unmount
+    dir=$(eval "echo \$$#")
+    if mount "$@"; then
+        # Use newlines to separate dirs, in case they contain spaces
+        if [ -z "$MARKED_MOUNTS" ]; then
+            MARKED_MOUNTS="$dir"
+        else
+            MARKED_MOUNTS="$dir
+$MARKED_MOUNTS"
+        fi
+    else
+        die "Could not mount $dir."
+    fi
+}
+
+umount_marked() {
+    echo "$MARKED_MOUNTS" | while read dir; do
+        # binfmt_misc might need to be unmounted manually, see LP #534211
+        if [ "$dir%/proc}" != "$dir" ] && 
+            ( [ "$VENDOR" = "Debian" ] || [ "$VENDOR" = "Ubuntu" ] ) &&
+            [ -d "$dir/sys/fs/binfmt_misc" ] && [ -f "$dir/mounts" ] &&
+            grep -q ^binfmt_misc "$dir/sys/fs/binfmt_misc" "$dir/mounts"; then
+            if ! umount "$dir/sys/fs/binfmt_misc"; then
+                echo "Couldn't unmount $dir/sys/fs/binfmt_misc." >&2
+            fi
+        fi
+        if ! umount "$dir"; then
+            echo "Couldn't unmount $dir." >&2
+        fi
+    done
 }
 
 if [ -f /usr/share/ltsp/ltsp-vendor-functions ]; then
