ltsp-chroot: Apply detect_arch and make it independent of lsb_release.

diff --git a/server/functions.d/Debian/ltsp-server-vendor-functions b/server/functions.d/Debian/ltsp-server-vendor-functions
--- a/server/functions.d/Debian/ltsp-server-vendor-functions
+++ b/server/functions.d/Debian/ltsp-server-vendor-functions
@@ -7,3 +7,21 @@ detect_arch() {
         echo "i386"
     fi
 }
+
+umount_marked() {
+    [ -z "$MARKED_MOUNTS" ] && return
+
+    echo "$MARKED_MOUNTS" | while read dir; do
+        # binfmt_misc might need to be unmounted manually, see LP #534211
+        if [ "$dir%/proc}" != "$dir" ] && 
+            [ -d "$dir/sys/fs/binfmt_misc" ] && [ -f "$dir/mounts" ] &&
+            grep -q "^binfmt_misc $dir/sys/fs/binfmt_misc" "$dir/mounts"; then
+            if ! umount "$dir/sys/fs/binfmt_misc"; then
+                echo "Couldn't unmount $dir/sys/fs/binfmt_misc." >&2
+            fi
+        fi
+        if ! umount "$dir"; then
+            echo "Couldn't unmount $dir." >&2
+        fi
+    done
+}
