Ubuntu: add armel support (defaults to the imx51 architecture and requires preparation described at https://wiki.ubuntu.com/ARM/BuildEABIChroot) as well as manual redboot netboot setup on the client

diff --git a/server/plugins/ltsp-build-client/Ubuntu/010-debootstrap b/server/plugins/ltsp-build-client/Ubuntu/010-debootstrap
--- a/server/plugins/ltsp-build-client/Ubuntu/010-debootstrap
+++ b/server/plugins/ltsp-build-client/Ubuntu/010-debootstrap
@@ -7,6 +7,15 @@ case "$MODE" in
             DEBOOTSTRAPOPTS="$DEBOOTSTRAPOPTS --include=$INCLUDE"
         fi
         # Install base packages
-        debootstrap $DEBOOTSTRAPOPTS --arch $ARCH $DIST $ROOT $MIRROR
+        case $ARCH in
+            armel)
+                debootstrap --foreign $DEBOOTSTRAPOPTS --arch $ARCH $DIST $ROOT $MIRROR
+                cp /usr/bin/qemu-arm-eabi "$ROOT"/usr/bin || echo "qemu-arm-eabi not found !"
+                chroot "$ROOT" debootstrap/debootstrap --second-stage
+            ;;
+            *)
+            debootstrap $DEBOOTSTRAPOPTS --arch $ARCH $DIST $ROOT $MIRROR
+            ;;
+        esac
         ;;
 esac
