Updated ltsp-update-sshkeys to also handle a -b basedir option, plus some cleanup

diff --git a/server/ltsp-update-sshkeys b/server/ltsp-update-sshkeys
--- a/server/ltsp-update-sshkeys
+++ b/server/ltsp-update-sshkeys
@@ -1,43 +1,68 @@
 #!/bin/sh
 
-test -z "$clients" && clients=$(find /opt/ltsp/. -mindepth 1 -maxdepth 1 -type d 2>/dev/null)
-hostname=$(hostname)
-ips=$(ip -o addr show | awk '$3 == "inet" && $4 !~ /^127\./ { print $4 }' | sed -e 's,/[0-9][0-9]*\>,,g')
-output=$(tempfile)
-enc="dsa rsa"
+#
+# Handle command line args
+#
 
-names="$hostname $ips"
+while getopts b: ARGS
+do
+    case ${ARGS} in
+        b)    BASE=$OPTARG
+              ;;
+       \?)    echo "Usage: $0 [-b ltspbase] [-p port] [-a architecture]"
+              exit 1
+              ;;
+       esac
+done
 
-logfile="/var/log/syslog"
+# Set up variables
+BASE=${BASE:-"/opt/ltsp"}
+test -z "${CHROOTS}" && \
+    CHROOTS=$(find ${BASE}/. -mindepth 1 -maxdepth 1 -type d 2>/dev/null | \
+              grep -v images)
+HOSTNAME=$(hostname)
+IPS=$(ip -o addr show | awk '$3 == "inet" && $4 !~ /^127\./ { print $4 }' | \
+      sed -e 's,/[0-9][0-9]*\>,,g')
+OUTPUT=$(tempfile)
+ENC="dsa rsa"
+NAMES="${HOSTNAME} ${IPS}"
+LOGFILE="/var/log/syslog"
 
-if [ -z "$clients" ]; then
-	logger -f $logfile -t ltsp "No client chroots found, please run ltsp-build-client"
+# Any chroots found?
+if [ -z "${CHROOTS}" ]; then
+	logger -f $LOGFILE -t ltsp \
+        "No client chroots found, please run ltsp-build-client"
 	exit 0
 fi
 
-for name in $names; do
-    for encryption in $enc; do
-		if [ -f /etc/ssh/ssh_host_${encryption}_key.pub ]; then
-			echo $(echo $name $(cat /etc/ssh/ssh_host_${encryption}_key.pub|awk '{split ($0, a, " "); print a[1]" "a[2]" "}')) >> $output
-			logger -f $logfile -t ltsp "# Creating ${encryption}-hostkey for $name"
+# Get encryption keys
+for NAME in ${NAMES}; do
+    for ENCRYPTION in ${ENC}; do
+		if [ -f /etc/ssh/ssh_host_${ENCRYPTION}_key.pub ]; then
+			echo $(echo $NAME $(cat /etc/ssh/ssh_host_${ENCRYPTION}_key.pub | \
+                awk '{split ($0, a, " "); print a[1]" "a[2]" "}')) >> $OUTPUT
+			logger -f $LOGFILE -t ltsp \
+                "# Creating ${encryption}-hostkey for ${NAME}"
 		else
-			logger -f $logfile -t ltsp "No ${encryption} key found for ${name}, please configure your ssh server correctly"
+			logger -f $LOGFILE -t ltsp \
+                "No ${ENCRYPTION} key found for ${NAME}, please configure your ssh server correctly"
 		fi
     done
 done
 
+# Add any additional hosts
 if [ -f /etc/ltsp/ssh_known_hosts.extra ]; then
-    cat /etc/ltsp/ssh_known_hosts.extra >> $output
+    cat /etc/ltsp/ssh_known_hosts.extra >> $OUTPUT
 fi
 
-for client in $clients; do
-    if [ -d $client/etc/ssh ]; then
-        install -m 644 $output $client/etc/ssh/ssh_known_hosts
+for CHROOT in ${CHROOTS}; do
+    if [ -d ${CHROOT}/etc/ssh ]; then
+        install -m 644 $OUTPUT ${CHROOT}/etc/ssh/ssh_known_hosts
     else
-        echo "WARNING: $client/etc/ssh not found. skipping..."
+        echo "WARNING: ${CHROOT}/etc/ssh not found. skipping..."
     fi
 done
 
-rm -f $output
+rm -f ${OUTPUT}
 
 exit 0
