merge pere@hungry.com--2005/ltsp--ubuntufixes--0--patch-57 Patches applied:
 * pere@hungry.com--2005/ltsp--ubuntufixes--0--patch-54
   Improve the error message when /var/lib/tftpboot/ltsp is missing.  Closes debian bug #331229.

 * pere@hungry.com--2005/ltsp--ubuntufixes--0--patch-55
   Make sure to exit if /var/lib/tftpboot/ltsp is missing.

 * pere@hungry.com--2005/ltsp--ubuntufixes--0--patch-56
   Udeb uses debconf, and should depend on ${misc:Depends}.

 * pere@hungry.com--2005/ltsp--ubuntufixes--0--patch-57
   Make sure ltsp-server-standalone installs properly even when dhcp3-server init.d script fail to restart.

diff --git a/server/ltsp-update-kernels b/server/ltsp-update-kernels
--- a/server/ltsp-update-kernels
+++ b/server/ltsp-update-kernels
@@ -6,6 +6,11 @@ TFTPBOOT=/var/lib/tftpboot/ltsp
 PXECFG=$TFTPBOOT/pxelinux.cfg
 LTSPROOT=/opt/ltsp
 
+if [ ! -d $TFTPBOOT ] ; then
+    echo "error: Directory $TFTPBOOT is missing.  Unable to continue"
+    exit 1
+fi
+
 for file in $LTSPROOT/*/boot/vmlinuz* $LTSPROOT/*/boot/initrd.img*; do
     cp -a -v "$file" $TFTPBOOT
 done
