nbdswapd: support name-based nbd exports.

diff --git a/server/nbdswapd b/server/nbdswapd
--- a/server/nbdswapd
+++ b/server/nbdswapd
@@ -6,6 +6,7 @@
 #  2008, Warren Togami <wtogami@redhat.com>
 #        Vagrant Cascadian <vagrant@freegeek.org>
 #        Eric Harrison <eharrison@k12linux.mesd.k12.or.us>
+#  2012, Alkis Georgopoulos <alkisg@gmail.com>
 #
 #  This program is free software; you can redistribute it and/or
 #  modify it under the terms of the GNU General Public License as
@@ -24,46 +25,70 @@
 #  MA 02110-1301, USA.
 #
 
+# Generates a swap file to be exported with nbd-server.
+#
+# When called with no parameters, it assumes that it was ran from inetd,
+# and it launches nbd-server in order to serve it.
+# An inetd configuration line like the following is needed in that case:
+# 9572 stream tcp nowait nobody /usr/sbin/tcpd /usr/sbin/nbdswapd
+#
+# When called with one parameter, it assumes that it was ran from nbd-server,
+# so it just creates the specified swap file and exits.
+# The nbd-server configuration section is expected to look similar to this:
+# [swap]
+# exportname = /tmp/nbd-swap/%s
+# prerun = nbdswapd %s
+# postrun = rm -f %s
 
-# generates a swap file and configures nbd-server to export it
-# to stdout. should usually be run from an inetd.
+# Fail on error, to notify nbd-server that the swap file wasn't created.
+set -e
 
-# default to running mkswap 
+# Default sparse swapfile size, in MB
+SIZE=512
+# Default to running mkswap 
 RUN_MKSWAP=true
-
+# Allow overriding the defaults from a configuration file
 if [ -f /etc/ltsp/nbdswapd.conf ]; then
     . /etc/ltsp/nbdswapd.conf
 fi
 
 # Abort if liveimg
-cat /proc/cmdline |/bin/grep -q "liveimg"
-[ $? -eq 0 ] && exit 0
-
-# swapfile size (in MB)
-SIZE=${SIZE:-"64"}
-
-if [ -n "$SWAPDIR" ]; then
-    if [ -d "$SWAPDIR" ] && [ -w "$SWAPDIR" ]; then
-        TEMPFILE_OPTS="${SWAPDIR}/XXXXXX"
-    else
-        echo "ERROR: not a directory or not writeable: $SWAPDIR" >&2
-        exit 1
-    fi
+if grep -q "liveimg" /proc/cmdline; then
+    exit 1
 fi
 
-if [ -z "$SWAP" ]; then
-    SWAP=$(mktemp $TEMPFILE_OPTS)
+test $# -eq 0 && inetd=true
+if [ -n "$inetd" ]; then
+    if [ -n "$SWAPDIR" ]; then
+        if [ -d "$SWAPDIR" ] && [ -w "$SWAPDIR" ]; then
+            TEMPFILE_OPTS="${SWAPDIR}/XXXXXX"
+        else
+            echo "ERROR: not a directory or not writeable: $SWAPDIR" >&2
+            exit 1
+        fi
+    fi
+
+    if [ -z "$SWAP" ]; then
+        SWAP=$(mktemp $TEMPFILE_OPTS)
+    fi    
+else
+    SWAP="$1"
+    SWAPDIR=${SWAP%/*}
+    test -d "$SWAPDIR" || mkdir -p "$SWAPDIR"
 fi
 
 # generate the swap file
-dd if=/dev/zero of=$SWAP bs=1024k count=0 seek=$SIZE 2> /dev/null
+dd if=/dev/zero of="$SWAP" bs=1M count=0 seek="$SIZE" 2> /dev/null
+chmod 600 "$SWAP"
 
 if [ "$RUN_MKSWAP" = "true" ]; then
-    /sbin/mkswap $SWAP > /dev/null 2>&1
+    mkswap "$SWAP" > /dev/null
 fi
 
-# start the swap server
-PATH=/usr/bin:/bin:$PATH nbd-server 0 $SWAP $NBD_SERVER_OPTS -C /dev/null > /dev/null 2>&1
+if [ -n "$inetd" ]; then
+    # start the swap server
+    nbd-server 0 "$SWAP" $NBD_SERVER_OPTS -C /dev/null > /dev/null 2>&1 || true
 
-# clean up the swap file
-rm -f $SWAP
+    # clean up the swap file
+    rm -f "$SWAP"
+fi
