nbdswapd: Add two cleanups suggested by Gadi.

diff --git a/server/nbdswapd b/server/nbdswapd
--- a/server/nbdswapd
+++ b/server/nbdswapd
@@ -20,7 +20,7 @@ if [ -n "$SWAPDIR" ]; then
     if [ -d "$SWAPDIR" ] && [ -w "$SWAPDIR" ]; then
         TEMPFILE_OPTS="${SWAPDIR}/XXXXXX"
     else
-        echo "ERROR: not a directory or not writeable: $SWAPDIR" 
+        echo "ERROR: not a directory or not writeable: $SWAPDIR" >&2
         exit 1
     fi
 fi
@@ -41,7 +41,7 @@ for NBDSERVER in /usr/bin/nbd-server /bin/nbd-server; do
     [ -x $NBDSERVER ] && break
 done
 
-$NBDSERVER 0 $SWAP $NBD_SERVER_OPTS -C /dev/null > /dev/null 2>&1
+PATH=/usr/bin:/bin:$PATH nbd-server 0 $SWAP $NBD_SERVER_OPTS -C /dev/null > /dev/null 2>&1
 
 # clean up the swap file
 rm -f $SWAP
