Go back to making local working directory first and scp in one shot, but remove local directory when finished with it and call mktemp on both sides to be safe.

diff --git a/localapps/ltsp-genmenu b/localapps/ltsp-genmenu
--- a/localapps/ltsp-genmenu
+++ b/localapps/ltsp-genmenu
@@ -1,22 +1,16 @@
 #!/bin/sh
 LANG=C
 
-do_ssh(){
-    ssh -S $LDM_SOCKET $LDM_SERVER "$@"
-}
-
-do_scp(){
-    scp -o "ControlPath $LDM_SOCKET" -o "User $USER" $1 $2
-}
-
 generate() {
     if [ -z ${TMP_XDG_DIR} ]; then
         exit
     fi
 
     # Make the working directory and subdirs
+    TMP_XDG_DIR_LOCAL="$(mktemp /tmp/ltsp-localapps-${USER}-XXXXXX)"
+
     for d in applications icons; do
-        do_ssh mkdir -p "${TMP_XDG_DIR}/${d}"
+        mkdir -p "${TMP_XDG_DIR_LOCAL}/${d}"
     done
 
     # Build desktop file list
@@ -36,10 +30,10 @@ generate() {
     # Cycle through all .desktop files in client's system applications dir
     for a in ${DESKTOP_FILES}; do
         # Copy client's .desktop file to local
-        do_scp ${a} ${LDM_SERVER}:${TMP_XDG_DIR}/applications/${a##*/}
+        cp ${a} ${TMP_XDG_DIR_LOCAL}/applications/${a##*/}
 
         # Change Exec and TryExec to our localapps command
-        do_ssh sed -i -e 's/^TryExec=\(.*\)/TryExec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' -e 's/^Exec=\(.*\)/Exec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' ${TMP_XDG_DIR}/applications/${a##*/} 
+        sed -i -e 's/^TryExec=\(.*\)/TryExec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' -e 's/^Exec=\(.*\)/Exec=xprop -root -f LTSP_COMMAND 8s -set LTSP_COMMAND "\1"/' ${TMP_XDG_DIR_LOCAL}/applications/${a##*/} 
 
         # Find the appropriate icon and copy it into the local icons dir
         ICON=$(grep ^Icon ${a}|sed -e 's/^Icon=\(.*\)/\1/')
@@ -49,19 +43,23 @@ generate() {
         # Else don't copy an icon
         if [ -n "${ICON}" ] && [ "${ICON}" = "${ICON##*/}" ]; then
             ICON=$(find -L /usr/share/icons /usr/share/pixmaps -type f -regex '.*'${ICON}'.*[png|xpm|svg]?'|head -1)
-            do_scp ${ICON} ${LDM_SERVER}:${TMP_XDG_DIR}/icons/${ICON##*/}
+            cp ${ICON} ${TMP_XDG_DIR_LOCAL}/icons/${ICON##*/}
         else
-            [ -e ${ICON} ] && do_scp ${ICON} ${LDM_SERVER}:${TMP_XDG_DIR}/icons/${ICON##*/} 
+            [ -e ${ICON} ] && cp ${ICON} ${TMP_XDG_DIR_LOCAL}/icons/${ICON##*/} 
         fi
     done
-    true
+
+    # now, scp the directory to the /tmp dir on the server
+    scp -r -o "ControlPath $LDM_SOCKET" -o "User $USER" ${TMP_XDG_DIR_LOCAL}/* ${LDM_SERVER}:${TMP_XDG_DIR}
+
+    # Clean up local
+    rm -rf ${TMP_XDG_DIR_LOCAL} || true
 }
 
 remove() {
     if [ -n "${TMP_XDG_DIR}" ];then
-        do_ssh rm -rf "${TMP_XDG_DIR}" 
+        ssh -S ${LDM_SOCKET} ${LDM_SERVER} rm -rf "${TMP_XDG_DIR}" || true
     fi
-    true
 }
 
 case "$1" in
