merged debian bzr tree from http://pkg-ltsp.alioth.debian.org/bzr/main

diff --git a/debian/ltsp-client.ltsp-client-setup.init b/debian/ltsp-client.ltsp-client-setup.init
--- a/debian/ltsp-client.ltsp-client-setup.init
+++ b/debian/ltsp-client.ltsp-client-setup.init
@@ -21,6 +21,8 @@ SCRIPTNAME=/etc/init.d/$NAME
 
 # Gracefully exit if the package has been removed.
 test -f /usr/lib/ltsp/ltsp_functions || exit 0
+# Gracefully exit if ltsp_chroot file is not present
+test -f /etc/ltsp_chroot || exit 0
 
 . /lib/lsb/init-functions
 . /usr/lib/ltsp/ltsp_functions
@@ -60,26 +62,38 @@ configure_console() {
 }
 
 configure_swap() {
-	if [ -n "$NBD_SWAP" ];then
-        if [ -z "$SWAP_SERVER" -a -z "$NBD_PORT" ]; then
-	        SWAP_SERVER=server
-	        NBD_PORT=9572
-        fi
-        cat <<EOF > /etc/nbd-client
-NBD_DEVICE[0]=/dev/nbd0
-NBD_TYPE[0]=s
-NBD_HOST[0]=$SWAP_SERVER
-NBD_PORT[0]=$NBD_PORT
-NBD_TYPE[0]=s
-EOF
-        if [ "$USE_LOCAL_SWAP" = "Y" ]; then
-            # Enable local swap partition if found on local disk
-            for part in `sfdisk -l 2>/dev/null | awk '/ 82 / { print $1}'`; do
-                mkswap $part
-                swapon $part
-            done
+    if [ "$USE_LOCAL_SWAP" = "Y" ]; then
+        # Enable local swap partition if found on local disk
+        for part in `sfdisk -l 2>/dev/null | awk '/ 82 / { print $1}'`; do
+            swap_devices="$swap_devices $part"
+        done
+    fi
+    if [ "$NBD_SWAP" = "Y" ]; then
+        SWAP_SERVER=${SWAP_SERVER:-"$SERVER"}
+        NBD_PORT=${NBD_PORT:-"9210"}
+        modprobe nbd
+        nbd-client $SWAP_SERVER $NBD_PORT /dev/nbd0 && swap_devices="$swap_devices /dev/nbd0"
+    fi
+    if [ "$ENCRYPT_SWAP" = "Y" ]; then
+        if [ -x /sbin/cryptsetup ]; then
+            modprobe dm_crypt
+        else
+            echo "ERROR: ENCRYPT_SWAP=Y, but /sbin/cryptsetup not found. disabling swap."
+            swap_devices=""
         fi
     fi
+    num=0
+    for device in $swap_devices ; do
+        swap="$device"
+        if [ "$ENCRYPT_SWAP" = "Y" ]; then
+            if [ -x /sbin/cryptsetup ]; then
+                cryptsetup -d /dev/urandom create swap$num $swap && swap="/dev/mapper/swap$num"
+                num=$(($num+1))
+            fi
+        fi
+        mkswap $swap
+        swapon $swap
+    done
 }
 
 configure_resolver() {
@@ -99,7 +113,7 @@ EOF
         cat /etc/hosts.ltsp >> /etc/hosts
     fi
 
-    if [ -n "$DNS_SERVER" -a -n "$SEARCH_DOMAIN" ]; then
+    if [ -n "$DNS_SERVER" ] && [ -n "$SEARCH_DOMAIN" ]; then
         cat <<EOF > /etc/resolv.conf
 search $SEARCH_DOMAIN
 nameserver $DNS_SERVER
@@ -200,12 +214,11 @@ configure_x() {
       fi
 
       # Mouse preseeding options.  Use inputattach if available
-      if type inputattach >/dev/null 2>/dev/null ; then
-        if [ $(echo "$X_MOUSE_DEVICE" | awk '/\/dev\/ttyS[0-9]/') ] && \
-	   [ i386 = $(dpkg --print-architecture) ] && \
-           [ -n "$X_MOUSE_PROTOCOL" ]; then
+      if [ -n "$X_MOUSE_DEVICE" ] && \
+        [ -n "$X_MOUSE_PROTOCOL" ] && \
+        type inputattach >/dev/null 2>/dev/null && \
+        [ -n "$(echo $X_MOUSE_DEVICE | awk '/\/dev\/ttyS[0-9]/')" ]; then
           inputattach --"$X_MOUSE_PROTOCOL" "$X_MOUSE_DEVICE" &
-        fi
       else
         if [ -n "$X_MOUSE_DEVICE" ]; then 
           preseed $xserver_package $xserver_package/config/inputdevice/mouse/port "$X_MOUSE_DEVICE"
