Debian: add check to see if DIST is supported by debootstrap - issue an error message explaning use of the --dist option (http://bugs.debian.org/472346)

diff --git a/server/plugins/ltsp-build-client/Debian/010-debootstrap b/server/plugins/ltsp-build-client/Debian/010-debootstrap
--- a/server/plugins/ltsp-build-client/Debian/010-debootstrap
+++ b/server/plugins/ltsp-build-client/Debian/010-debootstrap
@@ -6,6 +6,12 @@ case "$MODE" in
         if [ -n "$INCLUDE" ] ; then
             DEBOOTSTRAPOPTS="$DEBOOTSTRAPOPTS --include=$INCLUDE"
         fi
+        if [ -f "/usr/lib/debootstrap/scripts/$DIST" ]; then
+            echo "ERROR: invalid distribution: $DIST"
+            echo "you may need to specify the distribution with the --dist argument:"
+            echo "  $0 --dist etch"
+            exit 1
+        fi
         # Install base packages
         LC_ALL=C debootstrap $DEBOOTSTRAPOPTS --arch $ARCH $DIST $ROOT $MIRROR
         ;;
