- Refactored all architecture code to don't use dpkg for architecture discovering.  - Added support for error messages translation.

diff --git a/server/plugins/common/001-set-arch b/server/plugins/common/001-set-arch
--- a/server/plugins/common/001-set-arch
+++ b/server/plugins/common/001-set-arch
@@ -5,36 +5,39 @@ case "$MODE" in
     configure)
         if [ -n "$option_arch_value" ]; then
             ARCH_OPT="$option_arch_value"
-            case $ARCH_OPT in
-                i386)
-                    case $(dpkg --print-architecture) in
-                        amd64|ia64|i386)
-                            ARCH=i386
-                            ;;
-                        *)
-                            echo "ERROR: --arch i386 called on unsupported arch: "$(dpkg --print-architecture)
-                            exit 1
-                            ;;
-                    esac
-                    ;;
-                powerpc)
-                    case $(dpkg --print-architecture) in
-                        ppc64|powerpc)
-                            ARCH=powerpc
-                            ;;
-                        *)
-                            echo "ERROR: --arch powerpc called on unsupported arch: "$(dpkg --print-architecture)
-                            exit 1
-                            ;;
-                    esac
-                    ;;
-                *)
-                    echo "ERROR: unsupported --arch argument: "$ARCH_OPT
-                    exit 1
-                    ;;
-            esac      
         else
-            ARCH=$(dpkg --print-architecture)
+            ARCH_OPT=$(uname -m | sed -e s/i.86/i386/ -e s/x86.*/i386/ -e s/ppc.*/powerpc/)
         fi
+
+        # Validate the proposed architecture value.
+        case "$ARCH_OPT" in
+            i386)
+            case "$(uname -m)" in
+                x86_64|ia64|i386|i486|i586|i686)
+                ARCH=i386
+                ;;
+                *)
+                printf `eval_gettext "ERROR: --arch %s called on unsupported arch: %s"`, i386 $(uname -m)
+                exit 1
+                ;;
+            esac
+            ;;
+            powerpc)
+            case "$(uname -m)" in
+                ppc64|powerpc)
+                ARCH=powerpc
+                ;;
+                *)
+                printf `eval_gettext "ERROR: --arch %s called on unsupported arch: %s"`, powepc $(uname -m)
+                exit 1
+                ;;
+            esac
+            ;;
+            *)
+            printf `eval_gettext "ERROR: unsupported architecture. Check your --arch argument: %s"`, $ARCH_OPT
+			printf `eval_gettext "       supported values are: %s"`, "i386 powerpc"
+            exit 1
+            ;;
+        esac      
         ;;
 esac
